apiVersion: v1
kind: Pod 
metadata: 
  name: debug
  namespace: roboshop
  labels:
     project: roboshop
     environment: Dev
     purpose: debug
spec: 
  containers:
  - name: debug
    image: sravani3093/debug:4.0.0
 #to login to the pod
 #kubectl exec -it nginx -- bash
